version: "3.8"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  caddy:
    image: caddy:latest
    # https://hub.docker.com/_/caddy
    volumes:
      - phorge_web:/var/www/html
      - caddy_data:/data
    networks:
      - phorge
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: phorge_caddyfile
        target: /etc/caddy/Caddyfile
    environment:
      # https://caddyserver.com/docs/automatic-https#overview
      - DOMAIN=phorge.yourdomain.test

  mariadb:
    image: mariadb:latest
    # https://hub.docker.com/_/mariadb
    volumes:
      - phorge_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/phorge_db_password
    command: --innodb-buffer-pool-size=268435456 --local-infile=0 --max-allowed-packet=33554432 --sql-mode=STRICT_ALL_TABLES
    secrets:
      - phorge_db_password
    networks:
      - phorge_db

  phorge:
    image: zeigren/phorge:latest # ghcr.io/zeigren/phorge_docker:latest
    # https://hub.docker.com/r/zeigren/phorge
    volumes:
      - phorge_web:/var/www/html
      - phorge_ssh:/etc/ssh
      - phorge_repo:/var/repo
    environment:
      # set UPGRADE_ON_RESTART to true to update phorge
      - UPGRADE_ON_RESTART=true
      - PH_BASE_URI=https://phorge.yourdomain.test
      - PH_MYSQL_PASS=DOCKER-SECRET->phorge_db_password
      # - PH_CLUSTER_MAILERS=true
    networks:
      - phorge
      - phorge_db
    ports:
      # SSH Port
      - 2530:2530
    # configs:
    #   - source: phorge_mailers.json
    #     target: /usr/src/docker_ph/mailers.json
    secrets:
      - phorge_db_password

volumes:
  phorge_web:
  phorge_db:
  phorge_ssh:
  phorge_repo:
  caddy_data:

networks:
  phorge:
  phorge_db:

secrets:
  phorge_db_password:
    external: true

configs:
  phorge_caddyfile:
    external: true
  # phorge_mailers.json:
  #   external: true
